### ISSUE TITLE
Unable to save profile 

### ISSUE THREAD

**Issue by HenryHins** [serify-health/website#25]
When you click the "save" button to update your personal profile, it would say successful. But when you refresh it, it wasn't actually saved.

**Comment by wparad** [comment]
This is caused by using `ng-if` in the code.  This should only be used in placed in which we expect never to change for the live of web session.  Basically it removes all the handlers from the code.  In this case it prevented the models from getting attached back to the backend so the two-way binding broke.  When the user clicks on the save button the update doesn't happen because the model isn't being updated.

I'm not exactly sure why this part was changed, but it seemed related to the safari fixes.  We may have to revisit that change and find another way.
